name: continuous integration
on:
    push: 
        branches: 
            - main
            - test
    pull_request:

jobs:
    first-job:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: cache
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{runner.os}}-pip-${{hashFiles('requirements.lock')}}
                restore-keys: ${{runner.os}}-pip-
            - name: install dependencies
              run: pip install -r requirements.lock
            
            - name: build dependencies
              run: pip install build && python -m build --wheel

            - uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/*.whl
                retention-days : 7
            
    verify:
        needs: first-job
        runs-on : ubuntu-latest
        runsout-minutes: 10

        steps:
            - uses: actions/download-artifact@v4
                with: {name: dist}
            
            - run : pip install ./*.whl && python -c "import urlshort; print(urlshort.__version__)"

