name: ci 
on: 
  push: 
    branches: [main]
  pull-request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-verson: "3.11"
      - run: pip install -r requirement-dev.txt && pip install -e .
      - run : pytest -m "not slow"